default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000
  port: 5433

development:
  <<: *default
  database: my_twitter_development

test:
  <<: *default
  database: my_twitter_test

production:
  <<: *default
  database: my_twitter_production
